### ISSUE TITLE
`manifest.yml` should be added to npm package

### ISSUE THREAD

**Issue by JGAntunes** [racoonx2p/netlify-plugin-gmail#2]
Seems the current version published to`npm` is missing the `manifest.yml` (see - https://registry.npmjs.org/netlify-plugin-gmail/-/netlify-plugin-gmail-1.0.2.tgz)

This is most likely related to -  https://github.com/netlify/build-plugin-template/pull/19 - adding the `manifest.yml` to the `files` entry in the `package.json` should do it 👍

**Comment by trash-panda-v91-beta** [comment]
@JGAntunes You're right. Now it's fixed.
