### ISSUE TITLE
User/password auth method security concerns

### ISSUE THREAD

**Issue by JGAntunes** [racoonx2p/netlify-plugin-gmail#4]
![image](https://user-images.githubusercontent.com/5799039/104943023-0e5b2280-59ad-11eb-89f7-e7e07cbf1e08.png)

Given all the security implications this method implies we're wondering if it would be better not to support it altogether? OAuth forces you to scope the token access to a specific app/API and diminishes your potential surface of attack. For something like a Google account, this has the potential to cause a lot of damage. This method also seems to be dependent on disabling 2FA ☹️

**Comment by trash-panda-v91-beta** [comment]
I agree with this concerns and I removed user/pass auth.
